name: Deploy-CF-Test

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy-CF-Test
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiKey: ${{ secrets.CF_API_TOKEN }}
          email: ${{ secrets.CF_EMAIL }}
